### ISSUE TITLE
handle raw data to string conversion

### ISSUE THREAD

**Issue by ghost** [MadcapJake/fly-earl#2]
Hey!

Now filters and plugins, will receive the raw data as opposed to a string. This means if the filter/plugin is expecting a string, (for example fly-coffescript expects the source code to compile as a string) you need to convert the data to a string before you can call any String.prototype methods on it.

So, basically just convert the incoming `data` source to a string before passing it to Earl.

See [here](https://github.com/flyjs/fly/releases/tag/v0.6.0).

**Comment by MadcapJake** [comment]
Done and done! :+1:

**Comment by ghost** [comment]
Thank you!
